riz-l/one-ed-dashboard

- package-lock.json
- src/app/components/ReportSection/ReportSection.component.jsx
- src/app/components/ReportSection/ReportSection.elements.js
- src/app/pages/EDOverview/EDOverview.component.jsx
- src/app/pages/EDOverview/EDOverview.elements.js
- yarn.lock
- Amended `primaryNavigation`
- Amended `secondaryNavigation`
- Added conditional `grid-template-rows` for `primaryNavigation` and `secondaryNavigation` props
[ReportSection: Conditionally display primary/secondary navigations](https://app.gitkraken.com/glo/card/5ee3168dec98446e94158fe64f75cf1a)
> OED-4: Added conditional rendering/styling to ReportSection

- src/app/pages/Overview/subPages/Alerts/Alerts.elements.js
- src/app/pages/Overview/subPages/Allergies/Allergies.elements.js
- src/app/pages/Overview/subPages/Complaint/Complaint.elements.js
- src/app/pages/Overview/subPages/Complications/Complications.elements.js
- src/app/pages/Overview/subPages/Details/Details.elements.js
- src/app/pages/Overview/subPages/Diagnosis/Diagnosis.elements.js
- src/app/pages/Overview/subPages/Findings/Findings.elements.js
- src/app/pages/Overview/subPages/Procedures/Procedures.elements.js
- src/app/pages/Overview/subPages/Symptoms/Symptoms.elements.js
Adjusted `subPages` to remove border duplications
- `Overview/Details/Details`
- `Overview/History/Alerts`
- `Overview/History/Allergies`
- `Overview/History/Complications`
- `Overview/History/Diagnosis`
- `Overview/History/Findings`
- `Overview/History/Complaint`
- `Overview/History/Procedures`
- `Overview/History/Symptoms`
[Form: Adjust border duplications](https://app.gitkraken.com/glo/card/9fcc911e152f44b497868bd9613eccc2)
> OED-6: Adjusted border duplications for Overview subPages

- src/app/pages/Triage/Triage.component.jsx
- src/app/pages/Triage/subPages/Alerts/Alerts.component.jsx
- src/app/pages/Triage/subPages/Alerts/Alerts.elements.js
OED-10: I completed the Alerts section of Triage. I added the nav icon, changed the wrapper, and added the two report entries.
[Alerts](https://app.gitkraken.com/glo/card/b9f2d60eadcc425ea40ba65f8a7059ac)
> OED-10: completed the Alerts section of Triage

- src/app/pages/Triage/Triage.component.jsx
- src/app/pages/Triage/subPages/TriageAndStream/TriageAndStream.component.jsx
- src/app/pages/Triage/subPages/TriageAndStream/TriageAndStream.elements.js
OED-9: Completed the Triage and Stream subpage. I changed the forms from "grid.item" to "form.input", changed the Triage and Stream icon, and changed the wrapper to keep the consistent styling without the box around.
[Triage Subpage](https://app.gitkraken.com/glo/card/8d53e20907e74cc89103334652a883ec)
> OED-9: Completed the Triage and Stream subpage

- src/App.js
- src/app/components/Form/Form.component.jsx
- src/app/components/Input/Input.component.jsx
- src/app/components/Input/Input.elements.js
- src/app/pages/EDOverview/EDOverview.component.jsx
- src/app/pages/Login/Login.component.jsx
- src/app/pages/Overview/subPages/Details/Details.component.jsx
- src/utils/axios.js
Add Lorenzo token retrieval via a username/password authentication.
- Add a `Form`
- Add a username input field
- Add a password input field
- Use both the username and password values in a GET request to the Lorenzo .env URL
- Create a GET request to https://oneedfhirtest.azurewebsites.net/GetPatientList
- Edit the Form.Input to allow submit and password types
[Login: Add Lorenzo token retrieval](https://app.gitkraken.com/glo/card/8dc09fa0956d4fcc876d3466635a4e67)
> OED-8: Adding auth. token retrieval at Login

- src/App.js
- src/app/components/Form/Form.component.jsx
- src/app/components/Form/Form.elements.js
- src/app/pages/Login/Login.component.jsx
Transfer auth token from state into IndexedDB so it can be accessed throughout the app in Lorenzo API calls.
- Transfer auth token from state to IndexedDB on successful fetch
- Ensure auth token is cleared from IndexedDB on browser/tab close or on Logout
> OED-16: Auth token saved to IDB. Clears on logout/close.

- src/app/pages/Observations/Observations.component.jsx
- src/app/pages/Observations/Observations.elements.js
OED-19-updated template for Observations page.
1) Added: Container, ContentWrapper, Header, Wrapper to the Observations.elements file.
2) Imported the Container, ContentWrapper, Header, Wrapper from the elemenst file. 
3) Used Container, ContentWrapper, Header, Wrapper in the same way as they are used in Overview.component.
4) Imported and added Patient demographics component into Observations.component.
[Observations: Update the template for Observations page](https://app.gitkraken.com/glo/card/d39a41e6ad114281aaba5e759604878f)
> OED-19-updated template for Observations page

- src/app/pages/Seen/Seen.component.jsx
- src/app/pages/Seen/Seen.elements.js
OED-20-Seen Page Template updates
Details: 
1) Added: Container, ContentWrapper, Header, Wrapper to the Seen.elements file.
2) Imported the Container, ContentWrapper, Header, Wrapper from the elements file into Seen.component.
3) Used Container, ContentWrapper, Header, Wrapper in the same way as they are used in Overview.component.
4) Imported and added PatientDemographics.component into Seen.component.
[Seen: Update the template for Seen page](https://app.gitkraken.com/glo/card/e32eb84f808948d3868b4ea67c7144ce)
> OED-20-Seen Page Template updates

- src/app/pages/ClinicalNotes/ClinicalNotes.component.jsx
- src/app/pages/ClinicalNotes/ClinicalNotes.elements.js
OED21-Clinical Notes Template Updates
Details:
1) Added: Container, ContentWrapper, Header, Wrapper to the ClinicalNotes.elements file.
2) Imported the Container, ContentWrapper, Header, Wrapper from the elements file into ClinicalNotes.component.
3) Used Container, ContentWrapper, Header, Wrapper in the same way as they are used in Overview.component.
4) Imported and added PatientDemographics.component into ClinicalNotes.component.
[ClinicalNotes: Update the template for Clinical Notes page](https://app.gitkraken.com/glo/card/a1bd788a6d564eafa653b5bb6d51b693)
> OED21-Clinical Notes Template Updates

- src/app/pages/ViewSeen/ViewSeen.component.jsx
- src/app/pages/ViewSeen/ViewSeen.elements.js
OED-22-View Seen Template Updates
Details:
1) Added: Container, ContentWrapper, Header, Wrapper to the ViewSeen.elements file.
2) Imported the Container, ContentWrapper, Header, Wrapper from the elements file into ViewSeen.component.
3) Used Container, ContentWrapper, Header, Wrapper in the same way as they are used in Overview.component.
4) Imported and added PatientDemographics.component into ViewSeen.component.
[ViewSeen: Update the template for View Seen page](https://app.gitkraken.com/glo/card/873f7f7035d8495fa3b012f79a68e2a7)
> OED-22-View Seen Template Updates

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
- src/app/components/PatientDemographics/PatientDemographics.elements.js
OED-36: Patient Demographics Placeholder: Completed placeholder for the Patient Demographics component, adding all 14 fields.
[Patient Demographics Placeholder](https://app.gitkraken.com/glo/card/721e79415cf846af8f2cacc0ea5ec8f6)
> OED-36: Patient Demographics Placeholder

- src/app/pages/Settings/Settings.component.jsx
- src/app/pages/Settings/Settings.elements.js
OED-30: Completed Settings template page. I made the settings page fit inline with the rest of the One-ED app. No issues that I could see.
[Settings: Flesh out Settings template](https://app.gitkraken.com/glo/card/b9e818d93a92425cbb099196cb314210)
> OED-30: Completed Settings template page

- package-lock.json
- src/App.js
- src/app/components/PatientItem/PatientItem.component.jsx
- src/app/components/PatientItem/PatientItem.elements.js
- src/app/components/PatientList/PatientList.component.jsx
- src/app/components/PatientList/PatientList.elements.js
- src/app/components/ProtectedRoute/ProtectedRoute.component.jsx
- src/app/pages/Dashboard/Dashboard.component.jsx
- src/app/pages/Login/Login.component.jsx
- yarn.lock
Using the stored auth token (on successful claim set fetch), get and render Patient data.
- Create a call to access the stored `authToken`
- Make a successful API call to GetPatientList using the `authToken`
- Render any fetched data from the API
Added temporary `patientData` map to `PatientList`/`PatientItem`. Further styling/structuring is definitely needed.
[Dashboard: Get and render data in PatientList](https://app.gitkraken.com/glo/card/6eb3f4e9d9834e9596a5663d86c680d1)
> OED-24: Dashboard: Get and render data in PatientList

- src/app/components/PatientItem/PatientItem.component.jsx
- src/app/components/PatientItem/PatientItem.elements.js
- src/app/components/PatientList/PatientList.component.jsx
- src/app/components/PatientList/PatientList.elements.js
- src/app/pages/Dashboard/Dashboard.component.jsx
- src/app/pages/Dashboard/Dashboard.elements.js
Re-designed the `PatientItem` to accommodate mapped data from the Lorenzo GetPatientList API.
- Determine which fields/headings are required from API data
- Ensure appropriate fields/headings are passed as props to `PatientItem`
- Re-design `PatientItem` to suit/fit passed data
[PatientItem: Re-design to accommodate mapped data](https://app.gitkraken.com/glo/card/f40fbc3f398a4f0494098f2c2fffcd48)
> OED-41: Adding changes to PatientItem/PatientList

- src/app/components/Display/Display.component.jsx
- src/app/components/Display/Display.elements.js
- src/app/components/Display/Display.test.js
- src/app/components/Form/Form.component.jsx
- src/app/components/index.js
- src/app/pages/Training/Training.component.jsx
- src/app/pages/Triage/subPages/TriageAndStream/TriageAndStream.component.jsx
OED: Make Display Component. Made the display component and its relevant elements and test files. I also updated the form component so that the display component can also call the display component.
[Display: Create a Display component](https://app.gitkraken.com/glo/card/c0dc025dff3f49dfb7146bfc840d4403)
> OED-29: Make Display Component

- src/app/pages/Unauthorized/Unauthorized.component.jsx
- src/app/pages/Unauthorized/Unauthorized.elements.js
OED-45-Unauthorised page styling updates
Details: 
Adjust the visuals (colours, layout, etc.) of the Unauthorized page to better suit the global styling.
Adjust text colours to match those of the Home and Login pages.
Add white container w/border-radius, etc. same as home or Login.
Add an on hover colour change for the Link component.
[Unauthorized: Adjust visuals to fit global styling](https://app.gitkraken.com/glo/card/b80f047c2d1d4d6687aad06b174979d9)
> OED-45-Unauthorised page styling updates

- src/app/components/Indicator/Indicator.component.jsx
- src/app/components/Indicator/Indicator.elements.js
- src/app/components/Indicator/Indicator.test.js
- src/app/components/index.js
- src/app/pages/Training/Training.component.jsx
OED-43-Indicator Component
Details: 
Created an Indicator.component.jsx
Created an Indicator.element.js
Created an Indicator.test.js
Added an example of the component to the Training page.
[Indicator: Create an Indicator component](https://app.gitkraken.com/glo/card/fe1678b25f5d4346a54a69473fbf835a)
> OED-43-Indicator Component

- src/app/components/Display/Display.component.jsx
OED-54: Fixed the error in display.test.js
[Fix error in Display.test.js](https://app.gitkraken.com/glo/card/be3abcb024f745eb9387818851c5b7fa)
> OED:54-Fix Error in Display.test.js

- src/app/components/Button/Button.component.jsx
- src/app/components/Button/Button.elements.js
- src/app/pages/Login/Login.component.jsx
The `Login` form submit button is now coded as a `Form.Button`.
[Login: Cleanup submit button](https://app.gitkraken.com/glo/card/4ad82fdf07fc45d6808eb3bc612f59d9)
> OED-60: Aligned Login submit button to global theme

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
- src/app/pages/Triage/subPages/TriageAndStream/TriageAndStream.component.jsx
Minor corrections to PatientDemographics.component.jsx and TriageAndStream.component.jsx. As requested I made all of the "htmlfor=..." unique in the Patient Demographics component, and also alphabetised the imports in the Triage and Stream component,
> Minor corrections to PatientDemographics and TriageAndStream

- src/app/pages/AdmitOrReferral/subPages/DecisionToAdmit/DecisionToAdmit.test.js
- src/app/pages/Training/Training.test.js
OED-53-Fixed Training.test.js and DecisionToAdmit.test.js
Details: 
Fixed error in the .test.js files. No longer show errors when running npm test.
[Correct errors in Training.test.js and DecisionToAdmit.test.js](https://app.gitkraken.com/glo/card/bc7cc960a7c147efa7aaaf88f0ad4706)
> OED-53-Fixed Training.test.js and DecisionToAdmit.test.js

- src/app/components/Header/Header.component.jsx
Added user details (inc. username (e.g. LAYTON Josh) and role (e.g. administrator) to Header.
[Header: Access and display user details](https://app.gitkraken.com/glo/card/30319cf2956f4cc3a8e3ff0c6b41be24)
> OED-65: Adding user details (username and role) to Header

- src/app/components/Display/Display.elements.js
- src/app/components/Header/Header.component.jsx
- src/app/components/PatientItem/PatientItem.component.jsx
- src/app/components/PatientList/PatientList.component.jsx
- src/app/components/PatientSummary/PatientSummary.component.jsx
- src/app/pages/Login/Login.component.jsx
- src/redux/slices/selectedPatientSlice.js
- src/redux/store.js
`PatientSummary` now receives and renders data from the global store (redux). Visuals still need a lot of work, but importantly data is sent, received and rendered.
[PatientSummary: Re-design to accommodate mapped data/function as hero](https://app.gitkraken.com/glo/card/4af90d663e6e4621a3642b59bbfd4f07)
> OED-44: PatientSummary now receives and renders data from global store

- src/app/components/PatientSummary/PatientSummary.component.jsx
- src/app/pages/Overview/Overview.component.jsx
- src/app/pages/Overview/subPages/Details/Details.component.jsx
- src/redux/slices/patientListSlice.js
- src/redux/slices/selectedPatientSlice.js
- src/redux/slices/userDetailsSlice.js
Adjusted the APIs and rendered data into `Overview`/`Details`.
- Managed `.env` variables
- Pass/receive data to `Overview`/`Details`
- Render passed data
[App: Adjust APIs and render info to Overview](https://app.gitkraken.com/glo/card/dc8c609b52b4480e9432921aac8e92b3)
> OED-67: Renamed .env vars and rendered data in Details

- src/app/components/ReportEntry/ReportEntry.elements.js
- src/app/components/ReportSection/ReportSection.elements.js
- src/app/components/SecondaryNavigation/SecondaryNavigation.elements.js
- src/app/pages/Overview/Overview.component.jsx
- src/app/pages/Overview/subPages/Alerts/Alerts.component.jsx
- src/app/pages/Overview/subPages/Allergies/Allergies.component.jsx
- src/app/pages/Overview/subPages/Complaint/Complaint.component.jsx
- src/app/pages/Overview/subPages/Complications/Complications.component.jsx
- src/app/pages/Overview/subPages/Diagnosis/Diagnosis.component.jsx
- src/app/pages/Overview/subPages/Findings/Findings.component.jsx
- src/app/pages/Overview/subPages/Procedures/Procedures.component.jsx
- src/app/pages/Overview/subPages/Symptoms/Symptoms.component.jsx
- src/redux/slices/selectedPatientSlice.js
Pass and render data to ReportEntry components. Add conditions to determine red dot render.
- Pass data to `ReportEntry` components
- Render data in `ReportEntry` components
- Call GetAlerts
- Call GetAllergies
- Call GetConditions
[Overview: Pass/render data to ReportEntry components](https://app.gitkraken.com/glo/card/d8da483df2104544819e94fde678cfd1)
> OED-68: Passing and rendering data in Overview/Health History

- src/app/components/Attendance/Attendance.component.jsx
- src/app/components/Attendance/Attendance.elements.js
- src/app/components/Attendance/Attendance.styles.css
- src/app/components/Attendance/Attendance.test.js
- src/app/components/Attendance/subPages/CreateAttendance/CreateAttendance.component.jsx
- src/app/components/Attendance/subPages/CreateAttendance/CreateAttendance.elements.js
- src/app/components/Attendance/subPages/CreateAttendance/CreateAttendance.test.js
- src/app/components/Attendance/subPages/Registration/Registration.component.jsx
- src/app/components/Attendance/subPages/Registration/Registration.elements.js
- src/app/components/Attendance/subPages/Registration/Registration.test.js
- src/app/components/Attendance/subPages/index.js
- src/app/components/PatientList/PatientList.component.jsx
- src/app/components/index.js
OED-64-Create Modal for Attendance and add to Patient Details
Details:
- Create a new Modal component called Attendance. The modal is to be opened by clicking a button.
- Add the content of the current RegAndAttendance page to the new modal component
- Use the modal component in the Patient List component.
- Swap Create Attendance and Registration so the modal opens on Create Attendance.
- Create the form for the registration sub page
- Create the form for the Create Attendance sub page.
[Create Modal for Registration & Attendance.](https://app.gitkraken.com/glo/card/7efac2379c384b649efceae8b8045873)
> OED-64-Create Modal for Attendance and add to Patient Details

- src/app/components/Button/Button.component.jsx
- src/app/components/Button/Button.elements.js
- src/app/components/Display/Display.component.jsx
- src/app/components/Display/Display.elements.js
- src/app/components/Form/Form.component.jsx
- src/app/components/PageTitle/PageTitle.component.jsx
- src/app/components/PageTitle/PageTitle.elements.js
- src/app/components/PageTitle/PageTitle.test.js
- src/app/components/PatientSummary/PatientSummary.component.jsx
- src/app/components/index.js
- src/app/pages/Login/Login.component.jsx
- src/app/pages/Overview/Overview.component.jsx
- src/app/pages/Overview/Overview.elements.js
- src/app/pages/Overview/subPages/Details/Details.component.jsx
Rework and edit the `Display` and `Button` components. Also create a `PageTitle` component.
- `Display`: if !labelText remove `Label` margin-bottom
- `Button`: adjust margin
- Create a `PageTitle` component
[App: Display, Button PageHeading](https://app.gitkraken.com/glo/card/7a5d3d907eae4638aa7e1afbc9753f32)
> OED-75: Added PageTitle, amended Button and Display

- src/app/components/Button/Button.component.jsx
- src/app/components/Button/Button.elements.js
- src/app/components/Form/Form.component.jsx
- src/app/pages/Training/Training.component.jsx
- src/app/pages/Training/Training.elements.js
The `Button` component now accepts icon as a prop (inc, styling the .svg)
[Button: Add ability to accept icons](https://app.gitkraken.com/glo/card/4e34005418f14afab7b52e9187790f02)
> OED-77: Button now accepts icon as a prop

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
- src/app/components/ReportEntry/ReportEntry.component.jsx
- src/app/pages/Overview/subPages/Alerts/Alerts.component.jsx
- src/app/pages/Overview/subPages/Allergies/Allergies.component.jsx
OED-87: Alerts Modal.
-Accepted and Rendered the data
-Changed <UserIcon><UserIcon/> to <UserIcon/> on PatientDemographics.component.jsx as requested
> OED-87: Alerts Modal

- src/app/pages/Overview/subPages/Alerts/Alerts.component.jsx
- src/app/pages/Overview/subPages/Diagnosis/Diagnosis.component.jsx
OED-86: Diagnosis Model
-Accepted and rendered the data in the diagnosis modal
-Added labelText and htmlFor onto the alerts data
> OED-86: Diagnosis Modal

- src/app/pages/Overview/subPages/Symptoms/Symptoms.component.jsx
OED-90: Symptoms Modal
-Accepted and Rendered the data in the modal
> OED-90: Symptoms Modal

- src/app/pages/Seen/Seen.component.jsx
- src/app/pages/Seen/SubPages/SeenSubPage/SeenSubPage.component.jsx
- src/app/pages/Seen/SubPages/SeenSubPage/SeenSubPage.elements.js
- src/app/pages/Seen/SubPages/SeenSubPage/SeenSubPage.test.js
- src/app/pages/Seen/SubPages/index.js
- src/app/pages/Triage/Triage.component.jsx
- src/app/pages/Triage/subPages/TriageAndStream/TriageAndStream.component.jsx
OED-71-Allergies questions in Triage sub page and restyling of Seen page
Details:
- Add field Outcome (Dropdown options to go in comments for now to be added later)
- Add a Comments field.
- Add a small header for the above called "Check Allergies"
- Comment out the comments box (this will be uncommented later once the API is available)
Also made a few changes to the Seen page. 
Moved the form into its own subpage and matched the seen page styling to that of Triage page with a primary nav, secondary nav etc. 
[Add Allergies questions to the Triage & Stream Sub Page](https://app.gitkraken.com/glo/card/867d56f140c742b2b9247c1b28bd336f)
> OED-71-Allergies questions in Triage sub page and restyling of Seen page

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
- src/app/components/PatientDemographics/PatientDemographics.elements.js
OED-91: Patient Demographics: Accept Data
-The Patient Demographics Header now accepts and renders data
-The Patient Demographics Modal now accepts and renders data
> OED-91: Patient Demographics: Accept Data

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
- src/app/components/PatientDemographics/PatientDemographics.elements.js
Reverts riz-l/one-ed-dashboard#57.
Necessary revert to prevent `PatientDemographics` rendering issues
> Revert "OED-91: Patient Demographics: Accept Data"

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
OED-91: Neatening up the Patient Demographics component
-All imports are now alphabetised, and the spacing between different components should be correct
-Changed the states so that all data fields now pull from one state, and filter as required
> OED-91: Neatening up the Patient Demographics component

- src/app/components/MoveLocation/MoveLocation.elements.js
- src/app/pages/Seen/SubPages/SeenSubPage/SeenSubPage.component.jsx
- src/redux/slices/seenSlice.js
- src/redux/store.js
Adding PUT API requests for the SeenSubPage.
[API: Seen, PUT request](https://app.gitkraken.com/glo/card/4ac48b28b9274af5a0fdceb18a541c60)
> OED-100: SeenSubPage, PUT request

- src/app/components/ObsEntry/ObsEntry.component.jsx
- src/app/components/POPSHistoryModal/POPSHistoryModal.component.jsx
- src/app/components/POPSHistoryModal/POPSHistoryModal.elements.js
- src/app/components/POPSHistoryModal/SubPages/CEDObs/CEDObs.component.jsx
- src/app/components/POPSHistoryModal/SubPages/NeuroObs/NeuroObs.component.jsx
- src/app/components/POPSHistoryModal/SubPages/UrineObs/UrineObs.component.jsx
- src/app/pages/Triage/subPages/POPSHistory/POPSHistory.component.jsx
Added GET API requests for the POPS form which can be used in the modal to render data in the `Display` components.
[API: POPS Form, GET request](https://app.gitkraken.com/glo/card/131ddbcbbc0b4acb917953dc7b66e778)
> OED-98: Added data calls and renders to POPSHistoryModal and subPages

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
- src/app/components/PatientDemographics/PatientDemographics.elements.js
- src/app/components/PatientDetails/PatientDetails.component.jsx
- src/app/components/PatientDetails/PatientDetails.elements.js
- src/app/components/index.js
- src/app/pages/Overview/Overview.component.jsx
OED-102: Patient Demographics Modal and Clickable Fixes
-Changed the modal so that it imports the Overview section
-Changed the Overview section so it imports the newly-created PatientDetails component
-Created the Patient Details component, which is used in the Overview section and Patient Demographics section
[Patient Demographics Modal](https://app.gitkraken.com/glo/card/cd8d613f8e514453a71381e45d7d0cd0)
> OED-102: Patient Demographics Modal and Clickable Fixes

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
- src/app/components/PatientDemographics/PatientDemographics.elements.js
- src/app/components/PatientDetails/PatientDetails.elements.js
- src/app/components/PatientList/PatientList.component.jsx
- src/app/components/PatientSummary/PatientSummary.component.jsx
- src/app/components/PatientSummary/PatientSummary.elements.js
- src/app/pages/Overview/Overview.component.jsx
Add styling changes to `Overview` and `PatientSummary`.
[Overview, PatientSummary: Add styling changes](https://app.gitkraken.com/glo/card/3d3264a96fb1418d9110b9533ce123f6)
> MASTER: Added PatientDemographics and suggestion buttons to PatientSummary

- src/app/components/PatientDemographics/PatientDemographics.component.jsx
- src/app/components/PatientDemographics/PatientDemographics.elements.js
- src/app/components/ReportEntry/ReportEntry.component.jsx
- src/app/pages/Overview/subPages/Alerts/Alerts.component.jsx
- src/app/pages/Overview/subPages/Allergies/Allergies.component.jsx
- src/app/pages/Overview/subPages/Complications/Complications.component.jsx
- src/app/pages/Overview/subPages/Diagnosis/Diagnosis.component.jsx
- src/app/pages/Overview/subPages/Findings/Findings.component.jsx
- src/app/pages/Overview/subPages/PresentingComplaints/PresentingComplaints.component.jsx
- src/app/pages/Overview/subPages/Symptoms/Symptoms.component.jsx
OED-107: Overview Modals
-Changed the renders so that they have operators
-Imported and used the capitalizeFirstLetter function
-Changed the h3's to PageTitles
> OED-107: Overview Modals

- src/app/components/Header/Header.component.jsx
- src/app/components/ReportEntry/ReportEntry.component.jsx
- src/app/components/ReportEntry/ReportEntry.elements.js
- src/app/pages/Observations/Observations.component.jsx
- src/app/pages/Training/Training.component.jsx
- src/app/pages/Triage/subPages/Alerts/Alerts.component.jsx
- src/app/pages/Triage/subPages/Allergies/Allergies.component.jsx
Add changes pre-demo for further polish.
[App: Changes pre-demo](https://app.gitkraken.com/glo/card/6dee2a1393fc4fe5811fb94f436deb89)
> OED-108: Added last-minute visual polish changes

- src/App.js
- src/app/components/AddAlert/AddAlert.component.jsx
- src/app/components/Input/Input.component.jsx
- src/app/components/PatientList/PatientList.component.jsx
- src/app/components/SecondaryNavigation/SecondaryNavigation.elements.js
- src/app/pages/Overview/Overview.component.jsx
- src/app/pages/Overview/subPages/Procedures/Procedures.component.jsx
- src/redux/slices/selectedPatientSlice.js
- src/redux/store.js
Adding in Procedures ReportEntry to Patient Overview. Additionally making typo/format changes
> OED-1b: Adding in Procedures and typo fixes
